/**
 * VPhone Entry Point
 * Auto-generated by modularization script.
 */

import './00_init_helpers.js';
import './01_globals.js';
import './02_utils.js';
import './03_line_reg.js';
import './04_keyboard.js';
import './05_indexeddb.js';
import './06_ui_windows.js';
import './07_init_ui.js';
import './08_sip_status.js';
import './09_media_preload.js';
import './10_sip_client.js';
import './11_call_sessions.js';
import './12_blf_subscription.js';
import './13_chat_stream.js';
import './14_call_controls.js';
import './15_ui_views.js';
import './16_buddies_contacts.js';
import './17_stage_views.js';
import './18_settings_view.js';
import './19_presenters.js';
import './20_canvas_helpers.js';
import './21_dialogs.js';
import './22_watchdogs.js';
