const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = function testElectronDesktop() {
  const mainJs = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'main.js'), 'utf8');
  const preloadJs = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'preload.js'), 'utf8');
  const rendererJs = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'renderer', 'renderer.js'), 'utf8');
  const rendererHtml = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'renderer', 'index.html'), 'utf8');
  const phoneJs = fs.readFileSync(path.join(__dirname, '..', '..', 'Phone', 'phone.js'), 'utf8');
  const registerScript = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'scripts', 'register-smoke.cjs'), 'utf8');
  const packageJson = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'package.json'), 'utf8');
  const readme = fs.readFileSync(path.join(__dirname, '..', '..', 'README.md'), 'utf8');

  assert.match(mainJs, /setPermissionCheckHandler/);
  assert.match(mainJs, /["']media["']/);
  assert.match(mainJs, /["']speaker-selection["']/);
  assert.doesNotMatch(mainJs, /function\s+readEnvFile\s*\(/);
  assert.doesNotMatch(mainJs, /loadEnvConfig/);
  assert.doesNotMatch(mainJs, /BROWSER_PHONE_DESKTOP_ENV/);
  assert.doesNotMatch(mainJs, /SIP_USERNAME/);
  assert.match(mainJs, /VPHONE_DESKTOP_USER_DATA/);
  assert.match(mainJs, /app\.setPath\(["']userData["']/);
  assert.match(mainJs, /function\s+getDesktopAppTitle\s*\(/);
  assert.match(mainJs, /app\.setName\(appTitle\)/);
  assert.match(mainJs, /setAppUserModelId/);
  assert.match(mainJs, /vphone-desktop:log/);
  assert.match(mainJs, /vphone-desktop:focus-window/);
  assert.match(mainJs, /vphone-desktop:shortcut-action/);
  assert.match(mainJs, /globalShortcut/);
  assert.match(mainJs, /registerGlobalShortcuts/);
  assert.match(mainJs, /globalShortcut\.register/);
  assert.match(mainJs, /globalShortcut\.unregisterAll/);
  assert.doesNotMatch(mainJs, new RegExp('vphone-legacy' + '-desktop:'));
  assert.match(mainJs, /frame:\s*false/);
  assert.match(mainJs, /height:\s*453/);
  assert.match(mainJs, /minHeight:\s*453/);
  assert.match(mainJs, /maxHeight:\s*453/);
  assert.match(mainJs, /transparent:\s*true/);
  assert.match(mainJs, /roundedCorners:\s*true/);
  assert.match(mainJs, /backgroundColor:\s*['"]#00000000['"]/);
  assert.match(mainJs, /function\s+getDesktopWindowIcon\s*\(/);
  assert.match(mainJs, /function\s+getDesktopTrayIcon\s*\(/);
  assert.match(mainJs, /icon:\s*getDesktopWindowIcon\(desktopConfig\)/);
  assert.match(mainJs, /setAlwaysOnTop\(true/);
  assert.match(mainJs, /mainWindow\.show\(\);/);
  assert.match(mainJs, /mainWindow\.setAlwaysOnTop\(false\);/);
  assert.match(mainJs, /setTimeout\(finalizeFocus/);
  assert.match(mainJs, /showInactive\(\)/);
  assert.doesNotMatch(mainJs, /mainWindow\.on\(["']blur["']/);
  assert.match(mainJs, /app\.focus\(/);
  assert.match(mainJs, /did-finish-load/);
  assert.match(mainJs, /webContents\.on\(["']console-message["']/);
  assert.match(mainJs, /getLogFilePath/);
  assert.match(preloadJs, /requestMediaAccess/);
  assert.match(preloadJs, /VPhoneDesktop/);
  assert.match(preloadJs, /onShortcutAction/);
  assert.doesNotMatch(preloadJs, new RegExp('Browser' + 'PhoneDesktop'));
  assert.doesNotMatch(preloadJs, new RegExp('vphone-legacy' + '-desktop:'));
  assert.match(preloadJs, /focusWindow:/);
  assert.match(preloadJs, /minimizeWindow:/);
  assert.match(preloadJs, /closeWindow:/);
  assert.match(preloadJs, /log:/);
  assert.match(preloadJs, /getDiagnostics:/);
  assert.match(rendererJs, /normalizeDesktopPhoneConfig/);
  assert.match(rendererJs, /hasProvisionedAccount/);
  assert.match(rendererJs, /delete\s+normalized\.wssServer/);
  assert.match(rendererJs, /requestBrowserMediaAccess/);
  assert.match(rendererJs, /getUserMedia\(\{\s*audio:\s*true/);
  assert.match(rendererJs, /enumerateDevices\(\)/);
  assert.match(rendererJs, /selectAudioOutput/);
  assert.match(rendererJs, /TraceSip:\s*true/);
  assert.match(rendererJs, /focusWindow\('incoming-call'\)/);
  assert.match(rendererJs, /focusMountedPhone/);
  assert.match(rendererJs, /focusWindow/);
  assert.match(rendererJs, /mountedPhone\.iframe\.focus\(\)/);
  assert.match(rendererJs, /desktop-shortcut/);
  assert.match(rendererJs, /window\.VPhoneDesktop/);
  assert.match(rendererJs, /window\.Vphone\.mount/);
  assert.match(rendererJs, /minimizeWindow\(\)/);
  assert.match(rendererJs, /closeWindow\(\)/);
  assert.doesNotMatch(rendererJs, new RegExp('Browser' + 'Phone'));
  assert.match(registerScript, /readSettingsDevices/);
  assert.match(registerScript, /setFeatureToggle\([^,]+,\s*'auto'/);
  assert.match(registerScript, /setFeatureToggle\([^,]+,\s*'dnd'/);
  assert.match(registerScript, /receiverSentDnd/);
  assert.match(registerScript, /SIP\/2\.0 486 Do Not Disturb/);
  assert.match(registerScript, /Auto answer smoke failed/);
  assert.match(registerScript, /createDesktopConfig\(env,\s*1/);
  assert.match(registerScript, /createDesktopConfig\(env,\s*2/);
  assert.match(registerScript, /VPHONE_DESKTOP_USER_DATA/);
  assert.match(registerScript, /function\s+readEnvFile\s*\(/);
  assert.match(registerScript, /SIP_USERNAME/);
  assert.match(registerScript, /VPHONE_DESKTOP_CONFIG/);
  assert.match(registerScript, /DialByLine\('audio', '', '1235'\)/);
  assert.match(packageJson, /"test:register":\s*"node scripts\/register-smoke\.cjs"/);
  assert.match(packageJson, /"dist:win":\s*".*electron-builder --win"/);
  assert.match(packageJson, /"dist:mac":\s*".*electron-builder --mac"/);
  assert.match(packageJson, /"mac":\s*\{/);
  assert.match(packageJson, /"name":\s*"vphone"/);
  assert.match(packageJson, /"productName":\s*"VPhone"/);
  assert.match(packageJson, /"from":\s*"..\/..\/lib\/vphone\.min\.js"/);
  assert.doesNotMatch(packageJson, /vphone-legacy\.min\.js/);
  assert.match(rendererHtml, /<title>VPhone<\/title>/);
  assert.match(rendererHtml, /desktop-titlebar/);
  assert.match(rendererHtml, /id="phone-panel"[^>]*tabindex="-1"/);
  assert.match(rendererHtml, /data-window-action="minimize"/);
  assert.match(rendererHtml, /data-window-action="close"/);
  assert.doesNotMatch(registerScript, /Browser Phone Desktop/);
  assert.match(packageJson, /"buildLanguages":\s*\[\s*"en"\s*,\s*"vi"\s*\]/);
  assert.match(packageJson, /"desktop":\s*\{/);
  assert.match(packageJson, /"windowIcon":\s*"icons\/win\/icon\.ico"/);
  assert.match(packageJson, /"AppIcon":\s*"icons\/png\/128x128\.png"/);
  assert.match(readme, /## Runtime Modes/);
  assert.match(readme, /## Quick Start/);
  assert.match(phoneJs, /warmAudioCache\(audioBlobs\.Ringtone\)/);
  assert.match(phoneJs, /item\.blob = item\.url;/);
  assert.match(phoneJs, /onloadeddata = function\(e\)\s*\{/);

  const stylesCss = fs.readFileSync(path.join(__dirname, '..', '..', 'desktop', 'electron', 'renderer', 'styles.css'), 'utf8');
  assert.match(stylesCss, /html\s*,\s*body\s*\{[^}]*border-radius:\s*18px\s*;/s);
  assert.match(stylesCss, /\.desktop-titlebar\s*\{[^}]*-webkit-app-region:\s*drag\s*;/s);
  assert.match(stylesCss, /\.desktop-window-btn\s*\{[^}]*-webkit-app-region:\s*no-drag\s*;/s);
  assert.match(stylesCss, /\.shell\s*\{[^}]*border-radius:\s*18px\s*;/s);
  assert.match(stylesCss, /\.phone-panel\s*\{[^}]*border-radius:\s*0\s*;/s);
  assert.match(stylesCss, /body\s*\{[^}]*background:\s*transparent\s*;/s);
};

