const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = function testPhoneUiJs() {
  const js = fs.readFileSync(path.join(__dirname, '..', '..', 'Phone', 'phone.js'), 'utf8');
  const compactJs = js.replace(/\s+/g, '');
  const indexHtml = fs.readFileSync(path.join(__dirname, '..', '..', 'Phone', 'index.html'), 'utf8');
  const css = fs.readFileSync(path.join(__dirname, '..', '..', 'Phone', 'phone.css'), 'utf8');
  const libReadme = fs.readFileSync(path.join(__dirname, '..', 'README.md'), 'utf8');
  const libraryApi = fs.readFileSync(path.join(__dirname, '..', 'LIBRARY_API.md'), 'utf8');
  assert.match(js, /let\s+MaxDidLength\s*=\s*parseInt\(getDbItem\("MaxDidLength",\s*24\)\)/);
  assert.match(js, /function\s+GetSelfExtensionLabel\s*\(\)\s*\{/);
  assert.match(js, /var\s+selfExtension\s*=\s*GetSelfExtensionLabel\(\);/);
  assert.match(js, /html\s*\+=\s*"<div class=contactNameText><i class=\\"fa fa-phone\\"><\/i> "\+\s*selfExtension\s*\+"\s*<\/div>";/);
  assert.match(js, /html\s*\+=\s*"<div class=contactNameText><i class=\\"fa fa-phone\\"><\/i> "\+\s*GetSelfExtensionLabel\(\)\s*\+"\s*<\/div>";/);
  assert.match(js, /return hasServer && hasPort && hasUser;/);
  assert.match(js, /if\(HasInjectedSipConfig\(\)\)\s*\{\s*CreateUserAgent\(\);/);
  assert.match(js, /SIP account is not configured; open Settings to configure extension details/);
  assert.match(compactJs, /if\(NotificationsActive&&"Notification"inwindow\)\{if\(Notification\.permission==="granted"\)[\s\S]{0,600}?newNotification\(lang\.incoming_call/);
  assert.match(compactJs, /if\(NotificationsActive&&"Notification"inwindow\)\{if\(Notification\.permission==="granted"\)[\s\S]{0,600}?newNotification\(lang\.new_voice_mail/);
  assert.doesNotMatch(js, /function\s+ShowMyProfile\s*\(\)\s*\{\s*return\s*;/);
  assert.match(js, /Configure_Account_wssServer/);
  assert.match(js, /Configure_Account_WebSocketPort/);
  assert.match(js, /Configure_Account_ServerPath/);
  assert.match(js, /getDbItem\("ServerPath",\s*"\/ws"\)/);
  assert.match(js, /Configure_Account_SipDomain/);
  assert.match(js, /Configure_Account_SipPassword/);
  assert.doesNotMatch(js, /ToggleHeading\(this,'Appearance_Html'\)/);
  assert.doesNotMatch(js, /\$\("#tabBarRow"\)\.hide\(\);/);
  assert.match(js, /button\.toggleClass\("configPrimaryButton", i === 0\)/);
  assert.match(js, /button\.toggleClass\("configSecondaryButton", i !== 0\)/);
  assert.match(js, /function\s+ApplyDoNotDisturbState\s*\(\)\s*\{/);
  assert.match(js, /let\s+KeyboardShortcuts\s*=\s*NormalizeKeyboardShortcuts\(getDbItem\("KeyboardShortcuts"/);
  assert.match(js, /function\s+NormalizeKeyboardShortcuts\s*\(/);
  assert.match(js, /answer:\s*"F2"/);
  assert.match(js, /hangup:\s*"Escape"/);
  assert.match(js, /hold:\s*"F4"/);
  assert.match(js, /mute:\s*"F6"/);
  assert.match(js, /transfer:\s*"F8"/);
  assert.match(js, /dialpad:\s*"F9"/);
  assert.match(js, /function\s+HandleKeyboardShortcut\s*\(event\)/);
  assert.match(js, /if\(shortcutAction == "answer"\)[\s\S]{0,120}AnswerAudioCall/);
  assert.match(js, /if\(shortcutAction == "hangup"\)[\s\S]{0,220}RejectCall[\s\S]{0,220}cancelSession[\s\S]{0,220}endSession/);
  assert.match(js, /if\(shortcutAction == "hold"\)[\s\S]{0,220}unholdSession[\s\S]{0,220}holdSession/);
  assert.match(js, /if\(shortcutAction == "mute"\)[\s\S]{0,220}UnmuteSession[\s\S]{0,220}MuteSession/);
  assert.match(js, /if\(shortcutAction == "transfer"\)[\s\S]{0,180}StartTransferSession/);
  assert.match(js, /if\(shortcutAction == "dialpad"\)[\s\S]{0,80}ShowTab\("dialpad"\)/);
  assert.doesNotMatch(js, /btnMaximise/);
  assert.doesNotMatch(js, /btn-ShowDtmf/);
  assert.match(js, /btn-ShowNumpad/);
  assert.match(js, /function\s+ShowNumpad\s*\(lineNum\)/);
  assert.match(js, /function\s+AppendNumpadDtmf\s*\(lineNum,\s*digit\)/);
  assert.match(js, /function\s+SendNumpadDtmf\s*\(lineNum\)/);
  assert.match(js, /dtmfDialpadPopup/);
  assert.match(js, /dtmfInput/);
  assert.match(js, /dtmfClearButton/);
  assert.match(js, /window\.location\.reload\(\)/);
  assert.doesNotMatch(js, /Alert\(lang\.alert_settings,\s*lang\.reload_required/);
  assert.match(js, /incomingCallActions/);
  assert.match(js, /incomingCallDialButton/);
  assert.match(js, /transferPopupPanel/);
  assert.match(js, /transferPopupCard/);
  assert.match(js, /transferButtonRow/);
  assert.match(js, /transferActionButton/);
  assert.match(js, /txt-FindTransferBuddy"\)\.focus\(\)/);
  assert.doesNotMatch(js, /title=\\"Close\\" onclick=\\"event\.stopPropagation\(\); CancelConference/);
  assert.match(css, /\.dtmfNumpadPopup\s*\{/);
  assert.match(css, /\.dtmfInput\s*\{/);
  assert.match(css, /\.dtmfSendButton\s*\{/);
  assert.match(css, /\.incomingCallActions\s*\{/);
  assert.match(css, /\.incomingCallButton\s*\{/);
  assert.match(css, /\.transferPopupCard\s*\{/);
  assert.match(css, /\.transferButtonRow\s*\{/);
  assert.match(css, /\.transferActionButton\s*\{/);
  assert.doesNotMatch(js, /RejectCall\(lineObj\.LineNumber,\s*true\)/);
  assert.match(js, /RejectCall\(lineObj\.LineNumber,\s*486,\s*"Do Not Disturb"\)/);
  assert.match(js, /Call Waiting Disabled, rejecting call[\s\S]{0,180}RejectCall\(lineObj\.LineNumber,\s*486,\s*"Busy Here"\)/);
  assert.match(js, /\$\("#SettingsMenu"\)\.on\('click', function\(event\)\{[\s\S]{0,260}ShowMyProfile\(\);/);
  assert.match(js, /function\s+ToggleAutoAnswer\s*\(\)\s*\{[\s\S]{0,500}UpdateDialpadSettingButtons\(\);/);
  assert.match(js, /SyncMobileRegLink\(\);/);
  assert.match(js, /function\s+GetMobileRegistrationText\s*\(/);
  assert.match(js, /return\s+extension\s*\+\s*"\s+\(Online\)"/);
  assert.match(js, /return\s+extension\s*\+\s*"\s+\(Offline\)"/);
  assert.match(js, /RegistrationErrorText\s*=\s*response/);
  assert.match(js, /let\s+TransportManualDisconnect\s*=\s*false/);
  assert.match(js, /function\s+onTransportDisconnected\s*\([\s\S]*TransportManualDisconnect[\s\S]*ReconnectTransport\(\)/);
  assert.match(js, /\$\(window\)\.on\("online"[\s\S]*TransportManualDisconnect\s*=\s*false[\s\S]*ReconnectTransport\(\)/);
  assert.match(js, /function\s+PopulateSettingsDeviceOptions\s*\(/);
  assert.match(js, /PopulateSettingsDeviceOptions\(fallbackDeviceInfos/);
  assert.match(js, /function\s+ToggleRecentExpanded\s*\(/);
  assert.match(js, /function\s+GetRecentDisplayLabel\s*\(/);
  assert.match(js, /function\s+GetRecentDirectionIcon\s*\(/);
  assert.match(js, /function\s+FormatRecentLogTime\s*\(/);
  assert.match(js, /function\s+FormatFixedClockTime\s*\(/);
  assert.match(js, /function\s+FormatFixedDate\s*\(/);
  assert.match(js, /ParseUtcDisplayDate\(dateValue\)\.format\("HH:mm"\)/);
  assert.match(js, /\.local\(\)/);
  assert.match(js, /return\s+FormatFixedClockTime\(item\.ItemDate\)/);
  assert.match(js, /return\s+FormatFixedDate\(item\.ItemDate\)/);
  assert.match(js, /return\s+FormatDurationClock\(sec\)/);
  assert.match(js, /hours\s*\+\s*":"\s*\+\s*minutes\s*\+\s*":"\s*\+\s*seconds/);
  assert.match(js, /function\s+GetRecentDayLabel\s*\(/);
  assert.match(js, /recentDayDivider/);
  assert.doesNotMatch(js, /return GroupRecentEntries\(allCdrs\)/);
  assert.match(js, /recentCallItem enterpriseRecentItem/);
  assert.match(js, /recentCallAvatar/);
  assert.match(js, /recentDirectionAvatar/);
  assert.doesNotMatch(js, /recentCallIcon/);
  assert.match(js, /recentCallExpanded/);
  assert.doesNotMatch(js, /recentCountBadge/);
  assert.match(js, /recentActionCall/);
  assert.match(js, /recentActionAdd/);
  assert.match(js, /recentActionDelete/);
  assert.match(js, /data-recent-ids/);
  assert.match(js, /function\s+DeleteRecentGroupFromHistory\s*\(/);
  assert.match(js, /function\s+ToggleContactExpanded\s*\(/);
  assert.match(js, /function\s+BindContactExpandedActions\s*\(/);
  assert.match(js, /contactActionCall/);
  assert.match(js, /contactActionEdit/);
  assert.match(js, /contactActionDelete/);
  assert.match(js, /EditBuddyWindow\(rowObj\.attr\("data-contact-identity"\)\)/);
  assert.match(js, /RemoveBuddy\(rowObj\.attr\("data-contact-identity"\)\)/);
  assert.match(js, /function\s+ClearAllRecentHistory\s*\(/);
  assert.match(js, /function\s+ClearAllContacts\s*\(/);
  assert.match(js, /class=\\?"?UiWindowField contactFormPanel/);
  assert.match(js, /class=contactFormInputRow/);
  assert.match(css, /\.contactFormPanel\s*\{/);
  assert.match(css, /\.contactFormInputRow\s+\.UiInputText\s*\{/);
  assert.match(js, /function\s+HandleMobileClearTab\s*\(/);
  assert.match(js, /data-action=clear-tab/);
  assert.match(js, /data-tab=recents/);
  assert.match(js, /data-tab=contacts/);
  assert.match(js, /HandleMobileClearTab\(\$\(this\)\.attr\('data-tab'\)\s*\|\|\s*activeTab\)/);
  assert.match(js, /ClearAllRecentHistory\(\)/);
  assert.match(js, /ClearAllContacts\(\)/);
  assert.match(js, /if\(buddyObj\.type\s*!=\s*"contact"\)\s*continue;/);
  assert.match(js, /reasonCode\s*==\s*486[\s\S]{0,320}call_busy/);
  assert.match(js, /Confirm\([\s\S]*DeleteRecentGroupFromHistory/);
  assert.doesNotMatch(js, /recentActionDelete[\s\S]{0,300}DeleteRecentFromHistory\(rowObj\.attr\("data-owner-identity"\), rowObj\.attr\("data-cdr-id"\)\)/);
  assert.doesNotMatch(js, /\.slideDown\(120\)/);
  assert.doesNotMatch(js, /class=\\"roundButtons contactCompactCall\\" title=\\"G/);
  assert.doesNotMatch(js, /class=\\"roundButtons contactCompactMenu\\" title=\\"\+"\s*lang\.menu/);
  assert.match(css, /\.configExtensionForm\s*\{[^}]*overflow-y:\s*auto\s*;/s);
  assert.match(js, /function\s+RenderMainTabBar\s*\(/);
  assert.match(js, /function\s+RenderConfigActionBar\s*\(/);
  assert.match(js, /RenderConfigActionBar\(buttons\)/);
  assert.doesNotMatch(js, /\$\("#tabBarRow"\)\.hide\(\);\s*\$\("#actionArea"\)\.html\(html\);/);
  assert.match(css, /\.mainTabBar\.configActionBar\s*\{/);
  assert.match(css, /\.enterpriseRecentItem\s*\{/);
  assert.match(css, /\.enterpriseRecentItem\s*\{[^}]*flex:\s*0 0 auto\s*;/s);
  assert.match(css, /\.enterpriseRecentItem\s*\{[^}]*overflow:\s*visible\s*;/s);
  assert.match(css, /\.enterpriseRecentItem\.expanded\s*\{/);
  assert.match(css, /\.recentCallAvatar\s*\{/);
  assert.match(css, /\.recentCallExpanded\s*\{/);
  assert.match(css, /\.recentDayDivider\s*\{/);
  assert.match(css, /\.recentDirectionAvatar\s*\{/);
  assert.doesNotMatch(css, /\.recentCallIcon\s*\{/);
  assert.match(css, /\.contactCompactExpanded\s*\{/);
  assert.match(css, /\.contactActionEdit\s*\{/);
  assert.match(css, /\.enterpriseRecentItem\.expanded\s+\.recentCallExpanded\s*\{[^}]*display:\s*block !important\s*;/s);
  assert.match(indexHtml, /merged\.sip\.webSocketPort !== undefined\) merged\.WebSocketPort = merged\.sip\.webSocketPort/);
  assert.match(indexHtml, /merged\.sip\.serverPath !== undefined\) merged\.ServerPath = merged\.sip\.serverPath/);
  assert.match(indexHtml, /merged\.sip\.sipDomain !== undefined\) merged\.SipDomain = merged\.sip\.sipDomain/);
  assert.match(indexHtml, /merged\.sip\.username !== undefined\) merged\.SipUsername = merged\.sip\.username/);
  assert.match(indexHtml, /merged\.sip\.password !== undefined\) merged\.SipPassword = merged\.sip\.password/);
  assert.match(indexHtml, /window\.__VPhoneEmbedConfig/);
  assert.doesNotMatch(indexHtml, new RegExp('__Browser' + 'PhoneEmbedConfig'));
  assert.match(js, /window\.__VPhoneLangPacks/);
  assert.match(js, /window\.__VPhoneEmbeddedMedia/);
  assert.doesNotMatch(js, new RegExp('__Browser' + 'Phone'));
  assert.match(libReadme, /^# VPhone Library/m);
  assert.match(libReadme, /vphone\.min\.js/);
  assert.match(libReadme, /vphone\.min\.js/);
  assert.match(libReadme, /\| `title` \| `VPhone` \| Widget title\./);
  assert.match(libraryApi, /^# VPhone Library API Reference/m);
  assert.match(libraryApi, /name:\s*'VPhone'/);
  assert.match(libraryApi, /Vphone\.mount/);
  assert.doesNotMatch(libraryApi, /VPhone\.mount/);
  assert.doesNotMatch(js, /"#line-ui-"\s*\+\s*lineObj\.LineNumber\s*\+\s*"\s+\.presenceText"/);
  assert.doesNotMatch(js, /"#line-ui-"\s*\+\s*lineObj\.LineNumber\s*\+\s*"\s+\.contactNameText"/);
  assert.doesNotMatch(js, /<div class=presenceText style=\\"max-width:220px\\">/);
};
